config/routes.rb
Rails.application.routes.draw do

  root 'logins#new'
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  get '/password', to: 'volunteers#password'
  
  resources :queries
  get '/queryone', to: 'queries#one'
  get '/querytwo', to: 'queries#two'
  get '/querythree', to: 'queries#three'
  get '/queryfour', to: 'queries#four'
  get '/queryfive', to: 'queries#five'
  get '/querysix', to: 'queries#six'
  get '/queryseven', to: 'queries#seven'
  get '/queryeight', to: 'queries#eight'
  get '/querynine', to: 'queries#nine'
  get '/queryten', to: 'queries#ten'
  
  
  get '/request', to: 'projects#project'
  get '/requestevent', to: 'shorttermevents#event'
  
  resources :tools
  resources :sites
  resources :streets
  resources :parks 
  resources :washes
  resources :evaluationreports
  resources :reports
  resources :toolchecks
  resources :ceremonyawards
  resources :ceremonynotes
  resources :signs
  
  resources :shorttermevents do 
    resources :essigns
  end
  
  resources :volunteers do
    resources :organizations
    resources :groupcoordinators
    resources :regulatmembers
    resources :projects
  end

  resources :ceremonies do
    resources :ceremonyawards
    resources :ceremonynotes
    resources :signs
  end
  
  resources :organizations do
    resources :projects
    resources :evaluationreports
    resources :toolchecks
    resources :shorttermevents
  end
  resources :projects do
    resources :ceremonies
    resources :assigns
    resources :reports
  end
  get '/join-Organization', to: 'organizations#join'

end

app/models/tool.rb
class Tool < ActiveRecord::Base 
    has_many :toolchecks
def self.search(search)
  where("toolName LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%") 
end
    
def self.searchdate(search)
  where("created_at LIKE ? OR updated_at LIKE ?", "%#{search}%", "%#{search}%") 
end
    
    
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController 
	def index
		@tools = Tool.all
		if params[:search]
    		@tools = Tool.search(params[:search]).order("created_at DESC")
		else
    		@tools = Tool.all.order('created_at DESC')
		end
	end


	def new
		@tool = Tool.new
	end
	

	def create 
		@tool = Tool.new(tool_params)
		if @tool.save
			flash[:success] = "The Tool has been created succesfully"
			session[:tool_id] = @tool.id
			redirect_to    tools_path
		else
			render 'new'
		end
	end


	def edit
		@tool = Tool.find(params[:id])
	end


	def update
		@tool = Tool.find(params[:id])
		if @tool.update(tool_params)
			flash[:success] = "The Tool has been updated succesfully"
			redirect_to tools_path(@tool) #TODO change to users_path
		else
			render 'edit'
		end
	end


	def show
		@tool = Tool.find(params[:id])
	end

private
	def tool_params
		params.require(:tool).permit(:toolName, :totalQuantity, :availableQuantity, :description)
	end

end

app/views/tools/_form.html.erb
<%= render 'shared/errors', obj: @tool %>
<div>
	<div>
		<%= form_for @tool do |f| %>
		<h5>Tool Name:</h5>
		<%= f.text_field :toolName %>
		<h5>Total Tool Quantity:</h5>
		<%= f.text_field :totalQuantity %>
		<h5>Tool Description:</h5>
		<%= f.text_field :description %>

	
		<%= f.submit(@tool.new_record? ? "Create" : "Edit Tool", class:"btn btn-primary") %>
		<% end %>
	</div>
</div>

app/views/tools/_tool.html.erb
<tbody>
			<tr>
				<td><%= tool.toolName %></td>
				<td><%= tool.totalQuantity %></td>
				<td><%= tool.availableQuantity %></td>
				<td><%= tool.description %></td>
				<td><%= link_to tool_path(tool) do %>
                        <i class="glyphicon glyphicon-info-sign" style="color:#377bb5"></i>
                    <% end %>            
              		  <%= link_to edit_tool_path(tool) do %>
                        <i class="glyphicon glyphicon-cog" style="color:grey"></i>
                    <% end %>
                    </td>
			</tr>		
</tbody>
	

app/views/tools/edit.html.erb
<%= render 'shared/page_title', title: "Edit the Tool" %>
<%= render 'form' %>

app/views/tools/index.html.erb
<%= render 'shared/page_title', title: "All Tools" %>
<%= form_tag(tools_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Tool Name" %>
<%= submit_tag "Search" %>
<% end %>

<% if @tools.present? %>
<div class="table-container">
	<table class="data-table">
		<thead>
			<tr>
				<th>Tool Name</th>
				<th>Total Tool Quantity</th>
				<th>Total Available Quantity</th>
				<th>Tool Description</th>
				<th>Actions</th>
			</tr>
		</thead>
  <%= render @tools %>
  	</table>
</div>
<% else %>
  <p>There are no tools containing the name <%= params[:search] %>.</p>
<% end %>

app/views/tools/new.html.erb
<%= render 'shared/page_title', title: "Create the Tool" %>
<%= render 'form' %>

app/views/tools/show.html.erb
<%= render 'shared/page_title', title: "Tool Information" %>
<div class="col-lg-offset-1">
<div class="boarder-tool ">
<div class="col-lg-12 col-xs-12 ">
            <h3>Tool Information</h3> <hr style="height:1px;border:none;color:#333;background-color:#333;">
            <h4>Tool Name: <%= @tool.toolName %></h4>
            <h4>Total Tool Quantity: <%= @tool.totalQuantity %></h4>
			<h4>Quantity Available: <%= @tool.availableQuantity %></h4>
			<h4>Tool Description: <%= @tool.description %></h4>

</div>
</div>
</div>