config/routes.rb
Rails.application.routes.draw do

  root 'logins#new'
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  get '/password', to: 'volunteers#password'
  
  resources :queries
  get '/queryone', to: 'queries#one'
  get '/querytwo', to: 'queries#two'
  get '/querythree', to: 'queries#three'
  get '/queryfour', to: 'queries#four'
  get '/queryfive', to: 'queries#five'
  get '/querysix', to: 'queries#six'
  get '/queryseven', to: 'queries#seven'
  get '/queryeight', to: 'queries#eight'
  get '/querynine', to: 'queries#nine'
  get '/queryten', to: 'queries#ten'
  
  
  get '/request', to: 'projects#project'
  get '/requestevent', to: 'shorttermevents#event'
  
  resources :tools
  resources :sites
  resources :streets
  resources :parks 
  resources :washes
  resources :evaluationreports
  resources :reports
  resources :toolchecks
  resources :ceremonyawards
  resources :ceremonynotes
  resources :signs
  
  resources :shorttermevents do 
    resources :essigns
  end
  
  resources :volunteers do
    resources :organizations
    resources :groupcoordinators
    resources :regulatmembers
    resources :projects
  end

  resources :ceremonies do
    resources :ceremonyawards
    resources :ceremonynotes
    resources :signs
  end
  
  resources :organizations do
    resources :projects
    resources :evaluationreports
    resources :toolchecks
    resources :shorttermevents
  end
  resources :projects do
    resources :ceremonies
    resources :assigns
    resources :reports
  end
  get '/join-Organization', to: 'organizations#join'

end

app/models/project.rb
class Project < ActiveRecord::Base 
    belongs_to :organization
    belongs_to :site, :foreign_key => "site_id"
    has_many :ceremonies
    has_many :reports
    
def self.search(search)
  where("projectName LIKE ? OR projectLocation LIKE ? OR yearlyParticipants LIKE ? OR ifCanceled LIKE ? OR startDate LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
end
    
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
# before_action :admin_user, :current_user, only: :destroy
# before_action :require_same_user, only: [:edit, :update]
before_filter :assign_function

def assign_function
@var = 1
end
	
  def index
			@projects = Project.all
		if params[:search]
    		@projects = Project.search(params[:search]).order("created_at DESC")
		else
    		@projects = Project.all.order('created_at DESC')
		end
  end
    
    def project
      @projects = Project.where("site_id IS NULL")
    end

    
	def new
		@project = Project.new
	end
	
    def create
      @project = Project.new(project_params)

      if @project.save
        redirect_to :back
        flash[:success] =  'Your Project was successfully Requested!'
      else
        redirect_to :back
        flash[:success] = "Your Project wasn't requested!"
      end
    end
    
    def show
            @project = Project.find(params[:id])
    end
    
    def edit
		@project = Project.find(params[:id])
	  end

def update
    @project = Project.find(params[:id])
        if @project.update(project_params)
            flash[:success] = "Your Project Was Updated!"
            redirect_to project_path(@project)
        else
            render 'edit'
        end    
end
 
  private
    def project_params
      params.require(:project).permit(:organization_id, :site_id, :projectName, :projectLocation, :yearlyParticipants, :ifCanceled, :startDate)
    end


end

app/views/projects/_form.html.erb
<%= render 'shared/errors', obj: @project %>
<div>
	<div>
		<%= form_for @project do |f| %>
		
		<h5>Project Name:</h5>
		<%= f.text_field :projectName %>
		<h5>Project Location:</h5>
		<%= f.text_field :projectLocation %>
		<h5>Yearly Participants:</h5>
		<%= f.text_field :yearlyParticipants %>
		<h5>If Canceled (checked):</h5>
		<%= f.check_box :ifCanceled %>
		<h5>Project Start Date:</h5>
		<%= f.text_field :startDate, :id => "datepicker", :value => Date.today %>
	
		<%= f.submit(@project.new_record? ? "Create Project" : "Edit Project") %>
		<% end %>
	</div>
</div>

<script>
$('#datepicker').datepicker({format: 'yyyy-mm-dd'});
</script>

app/views/projects/_project.html.erb
<tr>
<td><%= project.projectName %> </td>
<td><%= project.organization.organizationName %> </td>
<td><%= project.projectLocation %> </td>
<td><%= project.yearlyParticipants %> </td>
<td><% if project.ifCanceled == true %>
                        <div class="glyphicon glyphicon-ok"></div>
                    <% else %>
                        <div class="glyphicon glyphicon-remove" style="color:red"></div>
                    <% end %></td>
<td><%= project.startDate.try(:strftime, "%m/%d/%Y")%> </td>
<td><%= link_to project_path(project) do %>
                <i class="glyphicon glyphicon-info-sign" style="color:#377bb5"></i>
<% end %>        
</tr>

app/views/projects/edit.html.erb
<%= render 'shared/page_title', title: "Edit the Project" %>
<%= render 'form' %>

app/views/projects/index.html.erb
<%= render 'shared/page_title', title: "All Projects" %>
<%= form_tag(projects_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Project Name" %>
<%= submit_tag "Search" %>
<% end %>

<% if @projects.present? %>
<div class="table-container">
	<table class="data-table">
		<thead>
			<tr>
				<th>Project Name</th>
				<th>Organization Name</th>
				<th>Project Location</th>
				<th>Yearly Participants</th>
				<th>If Canceled</th>
				<th>Start Date</th>
				<th>Actions</th>
			</tr>
		</thead>
  <%= render @projects %>
  	</table>
</div>
<% else %>
  <p>There are no Projects containing the name <%= params[:search] %>.</p>
<% end %>

app/views/projects/project.html.erb
<%= render 'shared/page_title', title: "All Projects without a Site" %>
<div class="table-container">
	<table class="data-table">
		<thead>
			<tr>
				<th>Project Name</th>
				<th>Organization Name</th>
				<th>Project Location</th>
				<th>Yearly Participants</th>
				<th>If Canceled</th>
				<th>Start Date</th>
				<th>Actions</th>
			</tr>
		</thead>
  <%= render @projects %>
  	</table>
</div>

app/views/projects/show.html.erb
<div class="col-lg-offset-1 col-lg-4 col-xs-4 ">
<div class="boarder-pro-info ">
<div class="col-lg-12 col-xs-12 ">
                <h3>Project Info</h3> <hr style="height:1px;border:none;color:#333;background-color:#333;">
				<h4>Project Name: <%= @project.projectName %></h4>
				<h4>Organization Name: <%= @project.organization.organizationName %></h4>
				<h4>Project Location: <%= @project.projectLocation %></h4>
				<h4>Yearly Participants: <%= @project.yearlyParticipants %></h4>
				<h4>If Canceled: <% if @project.ifCanceled == true %>
                        <div class="glyphicon glyphicon-ok"></div>
                    <% else %>
                        <div class="glyphicon glyphicon-remove" style="color:red"></div>
                    <% end %></h4>
				<h4>Start Date: <%= @project.startDate.try(:strftime, "%m/%d/%Y") %></h4>
				
			
				<h4><%= link_to "Edit Project", edit_project_path(@project), class:"btn btn-primary" %></h4>

</div>
</div>
</div>
<div class="col-lg-4 col-xs-4 col-lg-offset-2">
<div class="boarder-org ">
<div class="col-lg-12 col-xs-12 col-lg-offset-1">
	<h3>Project Actions</h3> 
<%= link_to "Create a new Ceremony", new_project_ceremony_url(@project), class:"btn btn-primary" %>
<%= link_to "Submit a new Report for the Project", new_project_report_path(@project), class:"btn btn-primary" %>
<% if @project.site_id == NIL %>
<%= link_to "Assign a Site to the Project", new_project_assign_path(@project), class:"btn btn-primary" %>
<% end %>			
</div>
</div>
</div>

</br>


<div class="col-lg-12">
<%= render 'shared/page_title', title: "Project Progress Reports"%> 
</div>
<div class="col-lg-12">
<div class="table-container">
	<table class="data-table">
		<thead>
			<tr>
				<th>Organization Name</th>
				<th>Project Name</th>
				<th>Work Done</th>
				<th>Number of Volunteers</th>
				<th>Total Hours Worked</th>
				<th>Date Last Worked</th>
				<th>Actions</th>


			</tr>
		</thead>
    <%= render(partial: 'reports/report', collection: @project.reports) %>
  	</table>
</div>
</br>

<div class="col-lg-12">
<%= render 'shared/page_title', title: "Ceremonies for the Project"%> 
</div>
<div class="col-lg-12">
<div class="table-container">
	<table class="data-table">
		<thead>
			<tr>
				<th>Organization Name</th>
				<th>Project Name</th>
				<th>Ceremony Name</th>
				<th>Location Preference</th>
				<th>Agreement Signed</th>
				<th>Date</th>
				<th>Actions</th>

			</tr>
		</thead>
    <%= render(partial: 'ceremonies/ceremony', collection: @project.ceremonies) %>
  	</table>
</div>