config/routes.rb
Rails.application.routes.draw do

  root 'logins#new'
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  get '/password', to: 'volunteers#password'
  
  resources :queries
  get '/queryone', to: 'queries#one'
  get '/querytwo', to: 'queries#two'
  get '/querythree', to: 'queries#three'
  get '/queryfour', to: 'queries#four'
  get '/queryfive', to: 'queries#five'
  get '/querysix', to: 'queries#six'
  get '/queryseven', to: 'queries#seven'
  get '/queryeight', to: 'queries#eight'
  get '/querynine', to: 'queries#nine'
  get '/queryten', to: 'queries#ten'
  
  
  get '/request', to: 'projects#project'
  get '/requestevent', to: 'shorttermevents#event'
  
  resources :tools
  resources :sites
  resources :streets
  resources :parks 
  resources :washes
  resources :evaluationreports
  resources :reports
  resources :toolchecks
  resources :ceremonyawards
  resources :ceremonynotes
  resources :signs
  
  resources :shorttermevents do 
    resources :essigns
  end
  
  resources :volunteers do
    resources :organizations
    resources :groupcoordinators
    resources :regulatmembers
    resources :projects
  end

  resources :ceremonies do
    resources :ceremonyawards
    resources :ceremonynotes
    resources :signs
  end
  
  resources :organizations do
    resources :projects
    resources :evaluationreports
    resources :toolchecks
    resources :shorttermevents
  end
  resources :projects do
    resources :ceremonies
    resources :assigns
    resources :reports
  end
  get '/join-Organization', to: 'organizations#join'

end

app/models/assign.rb
class Assign < ActiveRecord::Base 
    
def self.search(search)
  where("siteStreet LIKE ? OR siteCrossStreets LIKE ? OR siteCounty LIKE ? OR siteZip LIKE ? OR cityWardNumber LIKE ? OR countyDistrict LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
end
    
    
end

app/controllers/assigns_controller.rb
class AssignsController < ApplicationController
    	before_filter :assign_function

def assign_function
@var = 1
end

def new
      @sites = Site.all
if params[:search]
    		@sites = Site.search(params[:search]).order("created_at DESC")
	else
    		@sites = Site.all.order('created_at DESC')
end

@project = Project.find(params[:project_id])
       
end

end

app/views/assigns/new.html.erb
<%= render 'shared/page_title', title: "All Sites" %>
<ul class="nav nav-tabs">
    <li class="active">
		<%= link_to "All Sites", sites_path %>
	</li>

</ul>

<%= form_tag(new_project_assign_path(@project), :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Sites" %>
<%= submit_tag "Search" %>
<% end %>

<% if @sites.present? %>
<div class="table-container">
	<table class="data-table">
		<thead>
			<tr>
				<th>Subtype</th>
				<th>Site Street</th>
				<th>Cross-Streets</th>
				<th>County</th>
				<th>Zip Code</th>
				<th>City Ward Number</th>
				<th>County District</th>
				<th>Assign Site</th>

			</tr>
		</thead>
  <%= render @sites %>
  	</table>
</div>
<% else %>
  <p>There are no Sites containing the information <%= params[:search] %> exist.</p>
<% end %>