config/routes.rb
Rails.application.routes.draw do

  root 'logins#new'
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  get '/password', to: 'volunteers#password'
  
  resources :queries
  get '/queryone', to: 'queries#one'
  get '/querytwo', to: 'queries#two'
  get '/querythree', to: 'queries#three'
  get '/queryfour', to: 'queries#four'
  get '/queryfive', to: 'queries#five'
  get '/querysix', to: 'queries#six'
  get '/queryseven', to: 'queries#seven'
  get '/queryeight', to: 'queries#eight'
  get '/querynine', to: 'queries#nine'
  get '/queryten', to: 'queries#ten'
  
  
  get '/request', to: 'projects#project'
  get '/requestevent', to: 'shorttermevents#event'
  
  resources :tools
  resources :sites
  resources :streets
  resources :parks 
  resources :washes
  resources :evaluationreports
  resources :reports
  resources :toolchecks
  resources :ceremonyawards
  resources :ceremonynotes
  resources :signs
  
  resources :shorttermevents do 
    resources :essigns
  end
  
  resources :volunteers do
    resources :organizations
    resources :groupcoordinators
    resources :regulatmembers
    resources :projects
  end

  resources :ceremonies do
    resources :ceremonyawards
    resources :ceremonynotes
    resources :signs
  end
  
  resources :organizations do
    resources :projects
    resources :evaluationreports
    resources :toolchecks
    resources :shorttermevents
  end
  resources :projects do
    resources :ceremonies
    resources :assigns
    resources :reports
  end
  get '/join-Organization', to: 'organizations#join'

end

app/models/report.rb
class Report < ActiveRecord::Base 
    belongs_to :project
    
def self.search(search)
  where("numVolunteers LIKE ? OR totalHours LIKE ? OR dateLastWork LIKE ? OR workDone LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
end

end
    

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
# before_action :admin_user, :current_user, only: :destroy
# before_action :require_same_user, only: [:edit, :update]

  def index
    @var = 4
	@reports = Report.all
	if params[:search]
    	@reports = Report.search(params[:search]).order("created_at DESC")
	else
    	@reports = Report.all.order('created_at DESC')
	end
  end

	def new
	    @project = Project.find( params[:project_id])
		@report = Report.new
	end
	
def destroy
		@report = Report.find(params[:id])
		@report.destroy
		flash[:success] = "Report Deleted"
		redirect_to reports_path
end
  
    def create
      @report = Report.new(report_params)

      if @report.save
        redirect_to volunteer_path(current_user)
        flash[:success] =  'Your Report was successfully Saved!'
      else
        redirect_to :back
        flash[:success] = "Your Report wasn't Saved!"
      end
    end
def edit
		@report = Report.find(params[:id])
end
    
    def show
            @report = Report.find(params[:id])
    end

def update
    @report = Report.find(params[:id])
        if @Report.update(report_params)
            flash[:success] = "Your Report Was Updated!"
            redirect_to report_path(@report)
        else
            render 'edit'
        end    
  
end
 
  private
    def report_params
      params.require(:report).permit(:project_id, :workDone, :numVolunteers, :totalHours, :dateLastWork)
    end


end

app/views/reports/_form.html.erb
<%= render 'shared/errors', obj: @report %>
<div>
	<div>
		<%= form_for @report do |f| %>
		<%= f.hidden_field :project_id, :value => @project.id %>
		<h5>Work Done:</h5>
		<%= f.text_field :workDone %>
		<h5>Number of Volunteers:</h5>
		<%= f.text_field :numVolunteers %>
		<h5>Total Hours Worked:</h5>
		<%= f.text_field :totalHours %>
		<h5>Date Last Worked:</h5>
		<%= f.text_field :dateLastWork, :id => "datepicker", :value => Date.today %>
	
		<%= f.submit(@report.new_record? ? "Create Report" : "Edit Report", class:"btn btn-primary") %>
		<% end %>
	</div>
</div>

<script>
$('#datepicker').datepicker({format: 'yyyy-mm-dd'});
</script>

app/views/reports/_form1.html.erb
<%= render 'shared/errors', obj: @report %>
<div>
	<div>
		<%= form_for @report do |f| %>
		<%= f.hidden_field :project_id%>
		<h5>Work Done:</h5>
		<%= f.text_field :workDone %>
		<h5>Number of Volunteers:</h5>
		<%= f.text_field :numVolunteers %>
		<h5>Total Hours Worked:</h5>
		<%= f.text_field :totalHours %>
		<h5>Date Last Worked:</h5>
		<%= f.text_field :dateLastWork, :id => "datepicker", :value => Date.today %>
	
		<%= f.submit(@report.new_record? ? "Create Report" : "Edit Report", class:"btn btn-primary") %>
		<% end %>
	</div>
</div>

<script>
$('#datepicker').datepicker({format: 'yyyy-mm-dd'});
</script>

app/views/reports/_report.html.erb
<tbody>
			<tr>
			    <td><%= report.project.organization.organizationName %></td>
				<td><%= report.project.projectName %></td>
				<td><%= report.workDone %></td>
				<td><%= report.numVolunteers %></td>
				<td><%= report.totalHours %></td>
				<td><%= report.dateLastWork.try(:strftime, "%m/%d/%Y") %></td>
			
                <td>	<% if @var == 4%><%= link_to project_path(report.project) do %>
                        <i class="glyphicon glyphicon-info-sign" style="color:#377bb5"></i>
                    <% end %>
                    <% end %>   
              		  <%= link_to edit_report_path(report) do %>
                        <i class="glyphicon glyphicon-cog" style="color:grey"></i>
                        <% end %>
                        <%= link_to '',  report,  method: :delete, data: { confirm: 'Are you sure?' }, class:"glyphicon glyphicon-remove cog1" %>
	            	</td>
			</tr>		
</tbody>
	

app/views/reports/edit.html.erb
<%= render 'shared/page_title', title: "Edit The Progres Report" %>
<%= render 'form1' %>

app/views/reports/index.html.erb
<%= render 'shared/page_title', title: "Project Progress Reports" %>
<%= form_tag(reports_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Report Info" %>
<%= submit_tag "Search" %>
<% end %>


<% if @reports.present? %>
<div class="table-container">
	<table class="data-table">
		<thead>
			<tr>
			    <th>Organization Name</th>
				<th>Project Name</th>
				<th>Work Done</th>
				<th>Number of Volunteers</th>
				<th>Total Hours Worked</th>
				<th>Date Last Worked</th>
				<th>Actions</th>
			</tr>
		</thead>
  <%= render @reports %>
  	</table>
</div>
<% else %>
  <p>There are no report containing the name <%= params[:search] %>.</p>
<% end %>

app/views/reports/new.html.erb
<%= render 'shared/page_title', title: "Create a New Progress Report" %>
<%= render 'form' %>